In [76]:
import numpy as np
from pprint import pprint

def main_seq():
    for i, row in enumerate(A):
        for j, elem in enumerate(row):
            d[(i, j)] = seq(i, j)
    return max(d)
                
def check_constraint(a, b):
    return a + 1 == b or a - 1 == b

def seq(i, j):
    if (i, j) in d: return d[(i, j)]
        
    res = (1, [A[i][j]])
    right_valid = check_constraint(A[i][j], A[i][j + 1]) if j < (M - 1) else False
    down_valid = check_constraint(A[i][j], A[i + 1][j]) if i < (N - 1) else False
    
    if right_valid and down_valid:
        size_right, path_right = seq(i, j + 1)
        size_down, path_down = seq(i, j + 1)
        res = (size_right + 1, [A[i][j]] + path_right) if size_right > size_down else (size_down + 1, [A[i][j]] + path_down)
    elif right_valid:
        size, path_right = seq(i, j + 1)
        res = (size + 1, [A[i][j]] + path_right)
    elif down_valid:
        size, path_down = seq(i + 1, j)
        res = (size + 1, [A[i][j]] + path_down)
    
    d[(i, j)] = res
    return res

d = {}
A = np.array([[1,3,2,6,8], [-9,7,1,-1,2], [1,5,0,1,9]])
N, M = A.shape
main_seq()
print A
pprint(d)

[[ 1  3  2  6  8]
 [-9  7  1 -1  2]
 [ 1  5  0  1  9]]
{(0, 0): (1, [1]),
 (0, 1): (5, [3, 2, 1, 0, 1]),
 (0, 2): (4, [2, 1, 0, 1]),
 (0, 3): (1, [6]),
 (0, 4): (1, [8]),
 (1, 0): (1, [-9]),
 (1, 1): (1, [7]),
 (1, 2): (3, [1, 0, 1]),
 (1, 3): (1, [-1]),
 (1, 4): (1, [2]),
 (2, 0): (1, [1]),
 (2, 1): (1, [5]),
 (2, 2): (2, [0, 1]),
 (2, 3): (1, [1]),
 (2, 4): (1, [9])}


In [56]:
(1, 2) + (2, 3)

(1, 2, 2, 3)